//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingOrganizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Participants
    {
        public tbl_Participants()
        {
            this.tbl_Meetings = new HashSet<tbl_Meetings>();
        }
    
        public int ParticipantID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    
        public virtual ICollection<tbl_Meetings> tbl_Meetings { get; set; }
    }
}
